version: 2

jobs:
 lint:
  docker:
  - image: circleci/python:3.7.4-buster
  steps:
  - checkout
  - run: sudo pip install pylint
  - run: sudo pip install mypy
  - run: pylint bin/chroma-feedback chroma_feedback tests
  - run: mypy chroma_feedback/provider --no-strict-optional
 test:
  docker:
  - image: circleci/python:3.7.4-buster
  steps:
  - checkout
  - run: sudo pip install pytest
  - run: sudo pip install pytest-mock
  - run: sudo pip install mock
  - run: pytest tests

workflows:
 version: 2
 lint-and-test:
  jobs:
  - lint
  - test