version: 2

jobs:
 lint:
  docker:
  - image: circleci/python:3.9-buster
  steps:
  - checkout
  - run: pip install flake8
  - run: pip install mypy
  - run: pip install requests
  - run: pip install types-mock
  - run: pip install types-requests
  - run: flake8 bin/chroma-feedback chroma_feedback tests
  - run: mypy bin/chroma-feedback chroma_feedback tests
 test:
  docker:
  - image: circleci/python:3.9-buster
  steps:
  - checkout
  - run: sudo apt-get install libegl1
  - run: sudo apt-get install libxkbcommon0
  - run: sudo apt-get install libdbus-1-3
  - run: pip install mock
  - run: pip install pyqt6
  - run: pip install pytest
  - run: pip install pytest-mock
  - run: pip install requests
  - run: pytest tests

workflows:
 version: 2
 lint-and-test:
  jobs:
  - lint
  - test
