version: 2.1

orbs:
 python: circleci/python@3.1.0

jobs:
 lint:
  executor:
   name: python/default
   tag: '3.12'
  steps:
  - checkout
  - run: pip install flake8
  - run: pip install mypy
  - run: pip install requests
  - run: pip install types-mock
  - run: pip install types-requests
  - run: flake8 bin/chroma-feedback chroma_feedback tests
  - run: mypy bin/chroma-feedback chroma_feedback tests
 test:
  executor:
   name: python/default
   tag: '3.12'
  steps:
  - checkout
  - run: sudo apt install libegl1
  - run: sudo apt install libxkbcommon0
  - run: sudo apt install libdbus-1-3
  - run: pip install mock
  - run: pip install pyqt6
  - run: pip install pytest
  - run: pip install pytest-mock
  - run: pip install requests
  - run: pytest tests

workflows:
 lint-and-test:
  jobs:
  - lint
  - test
