version: 2

jobs:
 install:
  steps:
  - run: pip install coveralls
  - run: pip install pylint
  - run: pip install pytest
  - run: pip install pytest-cov
  - run: pip install pytest-mock
  - run: pip install mock
  - run: pip install mypy
 lint:
  docker:
  - image: circleci/python:3.7.4-buster
  steps:
  - checkout
  - install
  - run: pylint bin/chroma-feedback chroma_feedback tests
  - run: mypy chroma_feedback/provider --no-strict-optional
 test:
  docker:
  - image: circleci/python:3.6.6-stretch-browsers
  steps:
  - checkout
  - install
  - run: pytest tests

workflows:
 version: 2
 lint-and-test:
  jobs:
  - lint
  - test