version: 2

jobs:
 lint:
  docker:
  - image: circleci/python:3.9-buster
  steps:
  - checkout
  - run: sudo pip install .[dev]
  - run: pylint bin/chroma-feedback chroma_feedback tests
  - run: mypy bin/chroma-feedback chroma_feedback tests
 test:
  docker:
  - image: circleci/python:3.9-buster
  steps:
  - checkout
  - run: sudo pip install .[dev]
  - run: pytest tests

workflows:
 version: 2
 lint-and-test:
  jobs:
  - lint
  - test
